- name: variable in ansible
  hosts: mongodb
  # this is play level variables
  vars: 
    COURSE : devops
    TRAINER: harish
    DURATION: 110HRS
  tasks:
  - name: print hello world
    ansible.builtin.debug:
      msg: "Hello, Iam learning Ansible"
  - name: print veriables
    ansible.builtin.debug:
      msg: "Hello, iam learning {{COURSE}}, Trainer is {{TRAINER}}, Duration is {{DURATION}}"

