- name: variables from files
  hosts: localhost
  vars_files:
  - variable.yaml
  tasks: 
  - name: printing variables
    ansible.builtin.debug:
     msg: "Hello, iam learning {{NAME}}, Trainer is {{TRAINER}}, Duration is {{DURATION}}"
