- name: variables from files
  hosts: mongodb
  var_files:
  - variables.yaml
  tasks: 
   - name: printing variables
     ansible.builtin.debug:
       msg: "Hello, iam learning {{NAME}}, Trainer is {{TRAINER}}, Duration is {{DURATION}}"
