- name: variables in task level
  hosts: localhost
  vars:
  - money: "100000RS"
     land: "100AACRS"
  tasks:
  - name: inherit values from play
    ansible.builtin.debug:
      msg: "MONEY: {{money}}, LAND:{{land}}"
  - name: inherit values from play and add override
    vars:
    - money: "200000rs"
      houses: "3 houses"
    ansible.builtin.debug:
       msg: "MONEY: {{money}}, LAND:{{land}}, houses:{{houses}}"