- name: create user
  hosts: mongodb
  tasks: 
  - name: check user exists or not
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true
  - name: print the output
    ansible.builtin.debug:
      msg: "output is {{output}}"
